### ISSUE TITLE
select folder or multiple subtitles

### ISSUE THREAD

**Issue by dtrasca** [pckltr/corecteaza-subtitrari#1]
Hey, stiu ca e un rep dead si mort de cativa ani, dar zic ca e frumos sa poti face sa poti folosi proiectul tu asupra unui folder intreg sau a mai multor subtitrari deodata, pentru a salva timp. In loc sa facem un alt fork... Acum depinde de tine daca poti acest lucru <3

**Comment by mariusdmm** [comment]
ar fi foarte util

**Comment by pckltr** [comment]
Am adaugat optiunea de a alege mai multe fisiere.
